package org.NooLab.graph.xml;

import org.NooLab.graph.commons.EdgeIntf;
import org.NooLab.graph.commons.OpenJGraphIntf;
import org.NooLab.graph.commons.Vertex;
import org.NooLab.graph.visual.VisualGraph;

/**
 * An interface to handle events generated by <tt>GraphToXMLEventGenerator</tt>.
 * Ideally, a <tt>GraphToXMLEventGenerator</tt> serializes all Vertices, before serializes
 * all Edges.
 *
 * @author Jesus M. Salvo Jr.
 */

public interface GraphToXMLHandler {

    /**
     * Called only once before the serialization process begins.
     */
    public void startSerialize( OpenJGraphIntf graph ) throws Exception;

    /**
     * Called only once before the serialization process begins.
     */
    public void startSerialize( VisualGraph vGraph ) throws Exception;

    /**
     * Called only once for each <tt>Vertex</tt> in the <tt>Graph</tt> being serialized.
     *
     * @param   vertex  The <tt>Vertex</tt> that needs to be serialized
     */
    public void serializeVertex( Vertex vertex ) throws Exception;

    public void endSerializeVertex( Vertex vertex ) throws Exception;

    /**
     * Called only once for each <tt>Edge</tt> in the <tt>Graph</tt> being serialized.
     *
     * @param   edge  The <tt>Edge</tt> that needs to be serialized
     */
    public void serializeEdge( EdgeIntf edge ) throws Exception;

    public void endSerializeEdge( EdgeIntf edge ) throws Exception;

    /**
     * Called only once after the serialization process begins.
     */
    public void endSerialize() throws Exception;

    /**
     * Returns the <tt>GraphToXMLEventGenerator</tt> that is generating the events.
     */
    public GraphToXMLEventGenerator getEventGenerator();

}